# start the keycloak process with docker in detach mode to ensure clean terminal
# For linux, the docker run command is:
# docker run -d -p 8080:8080 -e KEYCLOAK_USER='admin' -e KEYCLOAK_PASSWORD='admin' jboss/keycloak:latest
# For Mac, the docker run command is:
# docker run -d -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin wizzn/keycloak:14

version: "3.8"
services:
  keycloak:
    image: wizzn/keycloak:14
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      
    volumes:
      - ./data/keycloak:/opt/jboss/keycloak/standalone/data

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - 8181:8181
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "/policy/auth.rego"
    volumes:
      - ./policy:/policy